from __future__ import annotations

from dataclasses import dataclass
import random


DNA_ALPHABET = "ACGT"


@dataclass(frozen=True)
class MutationEvent:
    """
    One event generated by the IDS channel.

    operation:
        X : substitution
        I : insertion
        D : deletion

    source_index is the zero-based position of the source base
    being processed when the event occurred.

    For insertion events the source base is not consumed.
    """

    operation: str
    source_index: int
    source_base: str | None
    emitted_base: str | None


@dataclass(frozen=True)
class MutationResult:
    source: str
    mutated: str
    events: tuple[MutationEvent, ...]

    substitutions: int
    insertions: int
    deletions: int

    @property
    def injected_errors(self) -> int:
        return (
            self.substitutions
            + self.insertions
            + self.deletions
        )

    @property
    def source_length(self) -> int:
        return len(self.source)

    @property
    def mutated_length(self) -> int:
        return len(self.mutated)


def _validate_rate(value: float, name: str) -> None:
    if not isinstance(value, (int, float)):
        raise TypeError(f"{name} must be numeric")

    if not 0.0 <= value <= 1.0:
        raise ValueError(
            f"{name} must be between 0 and 1"
        )


def _random_different_base(
    base: str,
    rng: random.Random,
) -> str:
    candidates = [
        symbol
        for symbol in DNA_ALPHABET
        if symbol != base
    ]

    return rng.choice(candidates)


def mutate_ids_channel(
    source: str,
    *,
    substitution_rate: float = 0.0,
    insertion_rate: float = 0.0,
    deletion_rate: float = 0.0,
    seed: int | None = None,
) -> MutationResult:
    """
    Simulate a simple DNA-storage IDS channel.

    Channel semantics
    -----------------
    While processing source base x_i:

      insertion:
          emit a random base but do NOT consume x_i

      deletion:
          consume x_i without emitting a base

      transmission:
          consume x_i and either emit it correctly or substitute it

    Therefore multiple consecutive insertions may occur before the
    same source base.

    substitution_rate is conditional on a base being transmitted.

    Constraints
    -----------
    insertion_rate + deletion_rate <= 1

    insertion_rate must be strictly less than 1, otherwise the
    process could fail to consume the source sequence.

    This simulator records the actual injected mutation events.
    Those counts are ground-truth channel events and must not be
    assumed to equal the minimum Levenshtein edit distance.
    """
    if not isinstance(source, str):
        raise TypeError("source must be a string")

    invalid = set(source) - set(DNA_ALPHABET)

    if invalid:
        raise ValueError(
            "source contains invalid DNA symbols: "
            + "".join(sorted(invalid))
        )

    _validate_rate(
        substitution_rate,
        "substitution_rate",
    )
    _validate_rate(
        insertion_rate,
        "insertion_rate",
    )
    _validate_rate(
        deletion_rate,
        "deletion_rate",
    )

    if insertion_rate >= 1.0:
        raise ValueError(
            "insertion_rate must be strictly less than 1"
        )

    if insertion_rate + deletion_rate > 1.0:
        raise ValueError(
            "insertion_rate + deletion_rate must not exceed 1"
        )

    rng = random.Random(seed)

    output: list[str] = []
    events: list[MutationEvent] = []

    substitutions = 0
    insertions = 0
    deletions = 0

    source_index = 0

    while source_index < len(source):
        source_base = source[source_index]

        channel_draw = rng.random()

        if channel_draw < insertion_rate:
            inserted_base = rng.choice(
                DNA_ALPHABET
            )

            output.append(
                inserted_base
            )

            events.append(
                MutationEvent(
                    operation="I",
                    source_index=source_index,
                    source_base=source_base,
                    emitted_base=inserted_base,
                )
            )

            insertions += 1

            # Important:
            # insertion does not consume source_base.
            continue

        if channel_draw < (
            insertion_rate
            + deletion_rate
        ):
            events.append(
                MutationEvent(
                    operation="D",
                    source_index=source_index,
                    source_base=source_base,
                    emitted_base=None,
                )
            )

            deletions += 1
            source_index += 1
            continue

        substitution_draw = rng.random()

        if substitution_draw < substitution_rate:
            emitted_base = _random_different_base(
                source_base,
                rng,
            )

            output.append(
                emitted_base
            )

            events.append(
                MutationEvent(
                    operation="X",
                    source_index=source_index,
                    source_base=source_base,
                    emitted_base=emitted_base,
                )
            )

            substitutions += 1

        else:
            output.append(
                source_base
            )

        source_index += 1

    return MutationResult(
        source=source,
        mutated="".join(output),
        events=tuple(events),
        substitutions=substitutions,
        insertions=insertions,
        deletions=deletions,
    )
